import { auth } from "@/lib/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="fr">
        <body>
          <Toaster richColors position="top-right" />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
