import Navbar from "./_components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({ children }) {
  return (
    <div className="flex h-full w-full flex-col items-center justify-center bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-400 to-blue-800">
      <div>
        <Navbar />
        {children}
      </div>
    </div>
  );
}
